# Generated by Django 2.0.2 on 2018-03-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('endereco', models.TextField()),
                ('rg', models.TextField()),
                ('cpf', models.TextField()),
                ('ctps', models.TextField()),
            ],
        ),
    ]
