# Generated by Django 2.0.2 on 2018-03-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotora',
            name='cpf',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promotora',
            name='ctps',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promotora',
            name='endereco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promotora',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='promotora',
            name='rg',
            field=models.CharField(max_length=100),
        ),
    ]
