# Generated by Django 2.0.2 on 2018-03-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fantasia',
            field=models.CharField(default='nao informado', max_length=100),
            preserve_default=False,
        ),
    ]
