# Generated by Django 2.0.2 on 2018-03-07 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20180306_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasting_date', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Cliente')),
                ('promotora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Promotora')),
            ],
        ),
    ]
