# Generated by Django 2.0.2 on 2018-03-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180308_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasting',
            name='tasting_date',
            field=models.DateField(verbose_name='Data da Degustação'),
        ),
    ]
