# Generated by Django 2.0.2 on 2018-03-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180309_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['codigo']},
        ),
    ]
